import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Arc Cloud documentation sidebar
 * Auto-generated from the docs-arc-cloud folder structure
 */
const sidebars: SidebarsConfig = {
  arcCloudSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
