import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Arc Enterprise documentation sidebar
 * Auto-generated from the docs-arc-enterprise folder structure
 */
const sidebars: SidebarsConfig = {
  arcEnterpriseSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
