import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Liftbridge documentation sidebar
 * Auto-generated from the docs-liftbridge folder structure
 */
const sidebars: SidebarsConfig = {
  liftbridgeSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
