import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Arc Launchpad documentation sidebar
 * Auto-generated from the docs-launchpad folder structure
 */
const sidebars: SidebarsConfig = {
  launchpadSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
